[versions]
kotlin = "2.2.0"
ksp = "2.2.0-RC3-2.0.2"
kotlin-jupyter = "0.13.0-481-1"
dataframe-core = "1.0.0-dev-7473"
publishPlugin = "1.9.23-dev-45"
ktlintGradle = "12.3.0"
intellijPlatformGradlePlugin = "2.6.0"
intellijPlatform = "252-EAP-SNAPSHOT" # TODO: lower to 2025.1.3 GA whenever released with required changes
intellijPluginRepositoryRestClient = "2.0.46"
intellijStructure = "3.307"

[libraries]
intellij-structure-ide = { group = "org.jetbrains.intellij.plugins", name = "structure-ide", version.ref = "intellijStructure" }
intellij-pluginRepositoryRestClient = { group = "org.jetbrains.intellij", name = "plugin-repository-rest-client", version.ref = "intellijPluginRepositoryRestClient" }
kotlin-jupyter-lib = { group = "org.jetbrains.kotlinx", name = "kotlin-jupyter-lib", version.ref = "kotlin-jupyter"}
dataframe-core = { group = "org.jetbrains.kotlinx", name = "dataframe-core", version.ref = "dataframe-core"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-jupyter-api = { id = "org.jetbrains.kotlin.jupyter.api", version.ref = "kotlin-jupyter" }
publisher = { id = "org.jetbrains.kotlin.libs.publisher", version.ref = "publishPlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
intellij-platform-base = { id = "org.jetbrains.intellij.platform.base", version.ref = "intellijPlatformGradlePlugin" }
