[versions]
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
kotlin-jupyter = "0.12.0-440"
publishPlugin = "1.9.23-dev-45"
ktlintGradle = "12.1.0"
intellijPlatformGradlePlugin = "2.6.0"
intellijPlatform = "2024.2"
intellijStructure = "3.305"

[libraries]
intellij-structure-ide = { group = "org.jetbrains.intellij.plugins", name = "structure-ide", version.ref = "intellijStructure" }
kotlin-jupyter-lib = { group = "org.jetbrains.kotlinx", name = "kotlin-jupyter-lib", version.ref = "kotlin-jupyter"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-jupyter-api = { id = "org.jetbrains.kotlin.jupyter.api", version.ref = "kotlin-jupyter" }
publisher = { id = "org.jetbrains.kotlin.libs.publisher", version.ref = "publishPlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
intellij-platform-base = { id = "org.jetbrains.intellij.platform.base", version.ref = "intellijPlatformGradlePlugin" }
